### ISSUE TITLE
Addition of CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by vinsdragonis** [khushilms-cs19/music-player-app#1]
The repository doesn't seem to have a `CODE_OF_CONDUCT.md` at the moment, though the repository's `README.md` says otherwise.
Could you please add this?

**Comment by khushilms** [comment]
Thank you for mentioning,
Actually i was working on this after downloading the base code from google drive of JS Mastery. I wasn't aware of the contents of readme file. Will change the contents.
